import { useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, BarChart3, Check, CheckCircle2, ChevronRight, Coffee, Code2, FileSpreadsheet, Globe, Menu, MessageCircle, Monitor, Package, QrCode, ShoppingBag, Sparkles, Store, UtensilsCrossed, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { DashboardPreview } from './dashboard-preview';
import cafeImage from '@/assets/cafe-interior.jpg';

export function Brand() { return <span className="brand"><span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 32 34" fill="none"><path d="M14 2 1 31h8l9-21-4-8ZM20 12l-5 12h8l3 7h7L20 12Z" fill="currentColor" /></svg></span><span>alvin<span className="font-medium">studio</span><span className="text-primary">.</span></span></span>; }
const solutions = [
  { icon: Globe, title: 'Website Business', text: 'Kesan pertama yang profesional. Website yang membangun kepercayaan dan membuka peluang baru.', items: ['Desain sesuai identitas bisnis', 'Optimal di semua perangkat', 'SEO dasar & loading cepat'] },
  { icon: QrCode, title: 'POS & QR Ordering', text: 'Dari pesanan hingga laporan. Satu sistem untuk operasional yang lebih cepat dan terorganisir.', items: ['Kasir & transaksi terintegrasi', 'QR menu & pemesanan digital', 'Inventory & laporan penjualan'] },
  { icon: Code2, title: 'Custom System', text: 'Setiap bisnis punya cara kerja unik. Kami membangun sistem yang mengikuti kebutuhanmu.', items: ['Alur kerja sesuai kebutuhan', 'Dashboard & monitoring bisnis', 'Solusi yang siap berkembang'] },
];
const pricing = [
  { name: 'Website', price: 'Rp600K', desc: 'Mulai hadir secara digital.', items: ['Landing page bisnis', 'Desain mobile-friendly', 'Informasi & kontak bisnis'] },
  { name: 'Company Profile', price: 'Rp800K', desc: 'Tampilkan bisnis lebih profesional.', items: ['Halaman profil perusahaan', 'Layanan & portfolio', 'SEO dasar'] },
  { name: 'Business Website', price: 'Rp1.2JT', desc: 'Lebih lengkap untuk bisnis kamu.', items: ['Website multi-halaman', 'Fitur sesuai kebutuhan', 'SEO dasar & optimasi'], popular: true },
  { name: 'POS / Custom', price: 'Custom', desc: 'Solusi yang mengikuti bisnismu.', items: ['POS & QR Ordering', 'Dashboard operasional', 'Scope sesuai kebutuhan'] },
];

export function StudioHome() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [consultationOpen, setConsultationOpen] = useState(false);
  const [service, setService] = useState('Konsultasi bisnis');
  const [copied, setCopied] = useState(false);
  const consult = (name = 'Konsultasi bisnis') => { setService(name); setCopied(false); setConsultationOpen(true); };
  const nav = [{ text: 'Solusi', id: 'solusi' }, { text: 'Produk', id: 'produk' }, { text: 'Project', id: 'project' }, { text: 'Cara Kerja', id: 'cara-kerja' }, { text: 'Harga', id: 'harga' }];
  return <>
    <header className="site-header"><div className="container-site flex h-full items-center justify-between"><a href="#" aria-label="Alvin Studio beranda"><Brand /></a><nav className="hidden items-center gap-7 text-xs font-medium text-muted-foreground md:flex" aria-label="Navigasi utama">{nav.map(n => <a key={n.id} href={`#${n.id}`} className="transition-colors hover:text-primary">{n.text}</a>)}</nav><div className="flex items-center gap-2"><Button variant="studio" className="hidden md:inline-flex" onClick={() => consult()}>Konsultasi Gratis <ArrowUpRight /></Button><Button variant="ghost" size="icon" className="md:hidden" aria-label={menuOpen ? 'Tutup menu' : 'Buka menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div></div>{menuOpen && <nav className="mobile-nav" aria-label="Navigasi seluler">{nav.map(n => <a key={n.id} href={`#${n.id}`} onClick={() => setMenuOpen(false)} className="text-sm">{n.text}</a>)}<Button variant="studio" onClick={() => { setMenuOpen(false); consult(); }}>Konsultasi Gratis <ArrowUpRight /></Button></nav>}</header>
    <main>
      <section className="hero"><div className="container-site"><span className="hero-badge"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Partner digital untuk bisnis kamu <ChevronRight size={12} className="text-muted-foreground" /></span><h1>Digital Solutions untuk<br className="hidden md:block" /> Bisnis yang <span className="text-primary">Ingin Berkembang</span></h1><p className="hero-copy">Website profesional, POS, QR Ordering, dan sistem custom untuk membantu bisnis berjalan lebih efektif.</p><div className="hero-actions"><Button variant="studio" onClick={() => consult()}>Konsultasi Gratis <ArrowUpRight /></Button><Button variant="studioOutline" asChild><a href="#project">Lihat Project <ArrowRight /></a></Button></div><p className="hero-note"><CheckCircle2 size={13} className="text-success" /> Solusi sesuai kebutuhan. Proses jelas. Siap berkembang.</p><div className="product-stage"><div className="stage-label"><span className="flex items-center gap-2 text-sm font-semibold"><Coffee size={18} /> cafe flow<span className="rounded border border-on-navy/25 px-1.5 py-0.5 text-[9px] font-normal">POS</span></span><span className="text-[10px] text-on-navy/65">Less busywork. More business.</span></div><DashboardPreview /></div></div></section>
      <div className="business-strip"><div className="container-site flex flex-wrap items-center justify-center gap-x-12 gap-y-4 text-xs text-muted-foreground"><span className="text-[11px]">Dibangun untuk bisnis seperti kamu</span>{[{ icon: Coffee, text: 'Cafe' }, { icon: UtensilsCrossed, text: 'Restaurant' }, { icon: Store, text: 'UMKM' }, { icon: ShoppingBag, text: 'Retail' }].map(({ icon: Icon, text }) => <span key={text} className="flex items-center gap-2 font-semibold text-foreground"><Icon size={17} strokeWidth={1.5} />{text}</span>)}</div></div>
      <section className="section"><div className="container-site"><div className="text-center"><p className="eyebrow">Tantangan bisnis</p><h2 className="section-heading">Bisnis berkembang.<br />Operasional jangan tertinggal.</h2><p className="section-copy">Hal kecil yang berulang bisa jadi hambatan besar untuk bisnismu.</p></div><div className="problem-grid">{[{ icon: FileSpreadsheet, title: 'Pesanan masih manual', text: 'Catatan tercecer, pesanan terlewat, dan antrian yang semakin panjang.' }, { icon: BarChart3, title: 'Data transaksi berantakan', text: 'Rekap memakan waktu. Sulit tahu angka penjualan yang sebenarnya.' }, { icon: Globe, title: 'Belum punya website', text: 'Calon pelanggan kesulitan menemukan dan mengenal bisnis kamu.' }, { icon: Monitor, title: 'Monitoring terasa sulit', text: 'Harus selalu di lokasi untuk tahu apa yang terjadi dalam bisnis.' }].map(({ icon: Icon, title, text }) => <div key={title}><span className="problem-icon"><Icon size={20} strokeWidth={1.6} /></span><h3 className="problem-title">{title}</h3><p className="section-copy text-xs">{text}</p></div>)}</div></div></section>
      <section className="section bg-muted" id="solusi"><div className="container-site"><div className="section-intro text-center"><p className="eyebrow">Solusi kami</p><h2 className="section-heading">Teknologi yang bekerja untuk bisnismu.</h2><p className="section-copy">Bukan sekadar digital. Tapi lebih praktis, lebih terukur, dan lebih siap tumbuh.</p></div><div className="solution-grid">{solutions.map(({ icon: Icon, title, text, items }, i) => <article key={title} className={`solution-card ${i === 1 ? 'featured' : ''}`}><div className="flex items-start justify-between"><span className="solution-icon"><Icon size={23} strokeWidth={1.6} /></span>{i === 1 && <span className="rounded bg-blue-soft px-2 py-1 text-[9px] font-semibold text-primary">Produk unggulan</span>}</div><h3>{title}</h3><p className="section-copy text-xs">{text}</p><ul>{items.map(item => <li key={item} className="flex items-center gap-2"><Check size={13} className="text-primary" />{item}</li>)}</ul><Button variant="link" className="mt-6 h-auto p-0 text-xs font-bold" onClick={() => consult(title)}>Diskusikan kebutuhan <ArrowRight /></Button></article>)}</div></div></section>
      <section className="section product-section" id="produk"><div className="container-site product-layout"><div><p className="eyebrow">Meet your next business tool</p><h2 className="section-heading">Cafe Flow POS<span className="text-primary">.</span><br />Satu sistem. Semua beres.</h2><p className="section-copy">Fokus menyajikan yang terbaik untuk pelanggan. Biar Cafe Flow membantu mengelola operasional di baliknya.</p><div className="feature-list">{[{ icon: ShoppingBag, text: 'POS' }, { icon: QrCode, text: 'QR Menu' }, { icon: Coffee, text: 'Orders' }, { icon: Package, text: 'Inventory' }, { icon: BarChart3, text: 'Reports' }].map(({ icon: Icon, text }) => <span className="feature-tag" key={text}><Icon size={12} className="text-primary" />{text}</span>)}</div><Button variant="studio" onClick={() => consult('Demo Cafe Flow POS')}>Diskusikan Cafe Flow <ArrowUpRight /></Button><p className="mt-3 text-[10px] text-muted-foreground">Preview produk · data ilustrasi</p></div><div className="product-preview"><DashboardPreview /></div></div></section>
      <section className="section bg-muted" id="project"><div className="container-site"><div className="section-intro flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Selected projects</p><h2 className="section-heading">Ide yang jadi solusi nyata.</h2><p className="section-copy">Eksplorasi produk dan website dari Alvin Studio.</p></div><span className="flex items-center gap-2 text-xs text-muted-foreground">Designed with purpose <Sparkles size={14} /></span></div><div className="portfolio-grid"><article><div className="portfolio-art portfolio-pos"><DashboardPreview /></div><div className="mt-5 flex items-center justify-between"><div><h3 className="text-lg font-bold">Cafe Flow POS</h3><p className="mt-1 text-xs text-muted-foreground">POS System · QR Ordering · Dashboard</p></div><Button variant="ghost" size="icon" aria-label="Diskusikan project Cafe Flow POS" onClick={() => consult('Cafe Flow POS')}><ArrowUpRight /></Button></div></article><article><div className="portfolio-art bg-blue-soft"><div className="website-preview"><div className="website-nav"><strong>RUANG KOPI<span className="text-primary">.</span></strong><span>Our story &nbsp;&nbsp; Menu &nbsp;&nbsp; Visit us</span></div><div className="website-cover"><img src={cafeImage} alt="Konsep website cafe dengan interior modern" width={1200} height={800} loading="lazy" /><div className="website-cover-text"><span className="text-[8px]">GOOD COFFEE. GOOD COMPANY.</span><h4 className="mt-3 text-2xl font-semibold">A little pause.<br />A better day.</h4><span className="mt-4 inline-flex items-center gap-2 border-b border-on-navy pb-1 text-[9px]">Explore our menu <ArrowRight size={10} /></span></div></div></div></div><div className="mt-5 flex items-center justify-between"><div><h3 className="text-lg font-bold">Business Website</h3><p className="mt-1 text-xs text-muted-foreground">Konsep Website · Brand Experience · Mobile-friendly</p></div><Button variant="ghost" size="icon" aria-label="Diskusikan project Business Website" onClick={() => consult('Business Website')}><ArrowUpRight /></Button></div></article></div></div></section>
      <section className="section" id="cara-kerja"><div className="container-site"><div className="text-center"><p className="eyebrow">Cara kerja</p><h2 className="section-heading">Proses jelas. Tanpa ribet.</h2><p className="section-copy">Dari obrolan pertama sampai solusi siap digunakan, kita berjalan bersama.</p></div><div className="steps">{[{ title: 'Consultation', text: 'Ceritakan bisnis, tantangan, dan tujuan kamu.' }, { title: 'Scope', text: 'Sepakati fitur, timeline, dan biaya yang transparan.' }, { title: 'Development', text: 'Kami membangun solusi dengan update berkala.' }, { title: 'Review', text: 'Cek bersama, beri masukan, dan sempurnakan.' }, { title: 'Handover', text: 'Solusi siap digunakan, lengkap dengan panduan.' }].map(({ title, text }, i) => <div className="step" key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p className="section-copy text-xs">{text}</p></div>)}</div></div></section>
      <section className="section bg-muted" id="harga"><div className="container-site"><div className="text-center"><p className="eyebrow">Investasi untuk bisnis</p><h2 className="section-heading">Mulai dari yang kamu butuhkan.</h2><p className="section-copy">Pilihan fleksibel untuk setiap tahap perkembangan bisnis.</p></div><div className="pricing-grid">{pricing.map(p => <article key={p.name} className={`price-card ${p.popular ? 'popular' : ''}`}>{p.popular && <span className="popular-label">PILIHAN BISNIS</span>}<h3 className="text-sm font-bold">{p.name}</h3><p className="mb-1 mt-5 text-[10px] text-muted-foreground">{p.price === 'Custom' ? 'Sesuai kebutuhan' : 'Mulai dari'}</p><div className="price-value">{p.price}</div><p className="text-[11px] text-muted-foreground">{p.desc}</p><ul className="price-features">{p.items.map(item => <li key={item} className="flex items-start gap-2"><Check size={12} className="shrink-0 text-primary" />{item}</li>)}</ul><Button variant={p.popular ? 'studio' : 'studioOutline'} className="w-full" onClick={() => consult(p.name)}>Konsultasi Gratis <ArrowUpRight /></Button></article>)}</div><p className="mt-6 text-center text-[11px] text-muted-foreground">Harga akhir menyesuaikan fitur dan kebutuhan project. Diskusikan dulu, tanpa komitmen.</p></div></section>
      <section className="final-cta"><div className="container-site flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[1.5px] text-on-navy/65">Your next chapter starts here</p><h2 className="text-[30px] font-bold leading-snug">Siap bawa bisnismu<br />ke level berikutnya?</h2><p className="mt-4 text-xs text-on-navy/65">Mulai dari obrolan sederhana. Kita temukan solusi yang tepat.</p></div><Button variant="studioLight" onClick={() => consult()}>Konsultasi Gratis <ArrowUpRight /></Button></div></section>
    </main>
    <footer className="footer"><div className="container-site"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><a href="#" aria-label="Alvin Studio beranda"><Brand /></a><p className="mt-3 text-xs text-muted-foreground">Digital solutions. Real business impact.</p></div><nav className="flex flex-wrap gap-6 text-xs text-muted-foreground" aria-label="Navigasi footer">{nav.filter(n => n.id !== 'cara-kerja').map(n => <a key={n.id} href={`#${n.id}`} className="hover:text-primary">{n.text}</a>)}</nav></div><div className="footer-bottom"><span>© 2026 Alvin Studio. All rights reserved.</span><span>Built with care, for growing businesses.</span></div></div></footer>
    <Dialog open={consultationOpen} onOpenChange={setConsultationOpen}><DialogContent><DialogHeader><DialogTitle>Konsultasi Gratis</DialogTitle><DialogDescription>Mari diskusikan kebutuhan {service === 'Konsultasi bisnis' ? 'bisnis kamu' : service}.</DialogDescription></DialogHeader><div className="contact-options"><MessageCircle className="mb-3 text-primary" size={24} /><p className="text-sm font-semibold">Kontak Alvin Studio akan segera tersedia.</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Simpan topik konsultasi untuk dibagikan saat kanal kontak tersedia. Belum ada pesan yang dikirim.</p></div><Button variant="studio" onClick={async () => { try { await navigator.clipboard.writeText(`Halo Alvin Studio, saya ingin konsultasi gratis tentang ${service}.`); setCopied(true); } catch { setCopied(false); } }}>{copied ? <><Check />Topik tersalin</> : <>Salin topik konsultasi <ArrowRight /></>}</Button></DialogContent></Dialog>
  </>;
}