import { ArrowRight, ArrowUpRight, Check, Coffee, Code2, Globe, QrCode, ShoppingBag, Store, UtensilsCrossed } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useSiteContent } from '@/hooks/use-site-content';

export function StudioHomeLive() {
  const { content } = useSiteContent();
  const nav=[['Solusi','solusi'],['Produk','produk'],['Project','project'],['Cara Kerja','cara-kerja'],['Harga','harga']];
  return <div className="min-h-screen bg-background text-foreground">
    <header className="site-header"><div className="container-site flex h-full items-center justify-between"><a href="/"><strong className="text-lg tracking-tight">alvin<span className="font-medium">studio</span><span className="text-primary">.</span></strong></a><nav className="hidden items-center gap-7 text-xs font-medium text-muted-foreground md:flex">{nav.map(([label,id])=><a key={id} href={'#'+id} className="hover:text-primary">{label}</a>)}</nav><Button variant="studio" asChild><a href="#cta">Konsultasi Gratis <ArrowUpRight/></a></Button></div></header>
    <main>
      <section className="hero"><div className="container-site"><span className="hero-badge">{content.hero.badge} <ArrowRight size={12}/></span><h1>{content.hero.title}</h1><p className="hero-copy">{content.hero.description}</p><div className="hero-actions"><Button variant="studio" asChild><a href="#cta">Konsultasi Gratis <ArrowUpRight/></a></Button><Button variant="studioOutline" asChild><a href="#project">Lihat Project <ArrowRight/></a></Button></div><p className="hero-note"><Check size={13} className="text-success"/> {content.hero.note}</p><div className="product-stage"><div className="stage-label"><span className="flex items-center gap-2 font-semibold"><Coffee size={18}/> {content.product.name}</span><span className="text-[10px] text-on-navy/65">Less busywork. More business.</span></div><div className="rounded-2xl bg-background p-5 shadow-xl"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground">Orders</p><p className="mt-2 text-xl font-bold">128</p></div><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground">Sales</p><p className="mt-2 text-xl font-bold">Rp8.4JT</p></div><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground">Products</p><p className="mt-2 text-xl font-bold">64</p></div><div className="rounded-xl border p-4"><p className="text-[10px] text-muted-foreground">Stock</p><p className="mt-2 text-xl font-bold">92%</p></div></div></div></div></div></section>
      <div className="business-strip"><div className="container-site flex flex-wrap justify-center gap-10 text-xs font-semibold text-muted-foreground"><span><Coffee className="mr-2 inline" size={16}/>Cafe</span><span><UtensilsCrossed className="mr-2 inline" size={16}/>Restaurant</span><span><Store className="mr-2 inline" size={16}/>UMKM</span><span><ShoppingBag className="mr-2 inline" size={16}/>Retail</span></div></div>
      <section className="section"><div className="container-site"><div className="text-center"><p className="eyebrow">Tantangan bisnis</p><h2 className="section-heading">Bisnis berkembang.<br/>Operasional jangan tertinggal.</h2></div><div className="problem-grid">{content.problems.map((x:any)=><div key={x.title}><span className="problem-icon"><Code2 size={20}/></span><h3 className="problem-title">{x.title}</h3><p className="section-copy text-xs">{x.text}</p></div>)}</div></div></section>
      <section className="section bg-muted" id="solusi"><div className="container-site"><div className="text-center"><p className="eyebrow">Solusi kami</p><h2 className="section-heading">Teknologi yang bekerja untuk bisnismu.</h2></div><div className="solution-grid">{content.solutions.map((x:any)=><article className="solution-card" key={x.title}><span className="solution-icon"><Globe size={23}/></span><h3>{x.title}</h3><p className="section-copy text-xs">{x.text}</p><ul>{x.items.map((i:string)=><li key={i} className="flex items-center gap-2"><Check size={13} className="text-primary"/>{i}</li>)}</ul><Button variant="link" className="mt-5 h-auto p-0">Diskusikan kebutuhan <ArrowRight/></Button></article>)}</div></div></section>
      <section className="section product-section" id="produk"><div className="container-site product-layout"><div><p className="eyebrow">Meet your next business tool</p><h2 className="section-heading">{content.product.name}<span className="text-primary">.</span><br/>Satu sistem. Semua beres.</h2><p className="section-copy">{content.product.description}</p><div className="feature-list">{content.product.features.map((f:string)=><span className="feature-tag" key={f}><QrCode size={12} className="text-primary"/>{f}</span>)}</div><Button variant="studio" asChild><a href="#cta">Diskusikan {content.product.name} <ArrowUpRight/></a></Button></div><div className="product-preview"><div className="rounded-2xl bg-background p-5 shadow-xl"><div className="mb-4 flex items-center justify-between"><span className="text-sm font-semibold">{content.product.name}</span><span className="rounded-full bg-blue-soft px-2 py-1 text-[9px] text-primary">LIVE PREVIEW</span></div><div className="space-y-3">{content.product.features.map((f:string,i:number)=><div key={f} className="flex items-center justify-between rounded-xl border p-3 text-xs"><span>{f}</span><span className="font-semibold">{[32,18,24,92,128][i] ?? 12}</span></div>)}</div></div></div></div></section>
      <section className="section bg-muted" id="project"><div className="container-site"><p className="eyebrow">Selected projects</p><h2 className="section-heading">Ide yang jadi solusi nyata.</h2><div className="portfolio-grid">{content.projects.map((p:any)=><article key={p.title}><div className="portfolio-art bg-blue-soft flex items-center justify-center p-6"><div className="w-full rounded-xl bg-background p-5 shadow-lg"><p className="text-xs font-semibold">{p.title}</p><p className="mt-2 text-[10px] text-muted-foreground">{p.subtitle}</p></div></div><div className="mt-5"><h3 className="text-lg font-bold">{p.title}</h3><p className="mt-1 text-xs text-muted-foreground">{p.subtitle}</p></div></article>)}</div></div></section>
      <section className="section" id="cara-kerja"><div className="container-site"><div className="text-center"><p className="eyebrow">Cara kerja</p><h2 className="section-heading">Proses jelas. Tanpa ribet.</h2></div><div className="steps">{content.process.map((p:any,i:number)=><div className="step" key={p.title}><span className="step-number">0{i+1}</span><h3>{p.title}</h3><p className="section-copy text-xs">{p.text}</p></div>)}</div></div></section>
      <section className="section bg-muted" id="harga"><div className="container-site"><div className="text-center"><p className="eyebrow">Investasi untuk bisnis</p><h2 className="section-heading">Mulai dari yang kamu butuhkan.</h2></div><div className="pricing-grid">{content.pricing.map((p:any)=><article className={`price-card ${p.popular?'popular':''}`} key={p.name}><h3 className="text-sm font-bold">{p.name}</h3><div className="price-value mt-5">{p.price}</div><p className="text-[11px] text-muted-foreground">{p.desc}</p><ul className="price-features">{p.items.map((i:string)=><li key={i} className="flex items-start gap-2"><Check size={12} className="text-primary"/>{i}</li>)}</ul><Button variant={p.popular?'studio':'studioOutline'} className="w-full" asChild><a href="#cta">Konsultasi Gratis <ArrowUpRight/></a></Button></article>)}</div></div></section>
      <section className="final-cta" id="cta"><div className="container-site flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="mb-3 text-[10px] font-semibold uppercase tracking-[1.5px] text-on-navy/65">Your next chapter starts here</p><h2 className="text-[30px] font-bold leading-snug">{content.cta.title}</h2><p className="mt-4 text-xs text-on-navy/65">{content.cta.description}</p></div><Button variant="studioLight" asChild><a href={content.settings.whatsapp ? 'https://wa.me/'+content.settings.whatsapp : '#'}>Hubungi Alvin Studio <ArrowUpRight/></a></Button></div></section>
    </main>
    <footer className="footer"><div className="container-site flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><strong>alvin<span className="font-medium">studio</span><span className="text-primary">.</span></strong><p className="mt-3 text-xs text-muted-foreground">{content.settings.tagline}</p></div><div className="text-xs text-muted-foreground">{content.settings.email || 'Kontak tersedia via WhatsApp'}</div></div></footer>
  </div>;
}
